version: '3'

services:

  # MySQL database service
  mysql:
    image: mysql:latest
    container_name: ecommerce-mysql
    environment:
      MYSQL_ROOT_PASSWORD: Abc123
      MYSQL_DATABASE: ecommerce
    ports:
      - "3306:3306"
    networks:
      - ecommerce

  spring-app:
#    image: zhoangp/spring-ecommerce:v6
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ecommerce-spring-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ecommerce
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Abc123
    networks:
      - ecommerce
    restart: on-failure

networks:
  ecommerce:
    driver: bridge
